### ISSUE TITLE
Create advanced modal

### ISSUE THREAD

**Issue by Heathercoraje** [Heathercoraje/pomotris-vh#23]
In this option, user can . . .
+ Type names of category 
+ Choose and assign colors for each category and save them

**Comment by Heathercoraje** [comment]
@veredrec I think we will need to have a short meeting to decide how and what data needs to be stored once user input categories and colors.

**Comment by veredrec** [comment]
Sure @Heathercoraje! let's do it!

**Comment by Heathercoraje** [comment]
so we've decided that user can have max 4 different categories.
Categories and colors setting will be on the same modal, just on different view.
and Dashboard will have Categories/colors data/ total time for each category
