### ISSUE TITLE
Represent pomodoro time in squares

### ISSUE THREAD

**Issue by veredrec** [Heathercoraje/pomotris-vh#4]
Make the logic to generate squares for time spent in pomodoro intervals

**Comment by Heathercoraje** [comment]
I find [this](https://codepen.io/nataliecardot/pen/MQRxJZ?editors=0010) today from one of my tweet's follower's codepen. Table for grids!

**Comment by veredrec** [comment]
Looks great! I will look at the code and see if we can implement something similar!

**Comment by veredrec** [comment]
Started to generate squares on the page, but no data is bind to them yet. The code is in the `record-board` branch
