### ISSUE TITLE
validate category and remove if it is repetitive

### ISSUE THREAD

**Issue by Heathercoraje** [Heathercoraje/pomotris-vh#44]
When a user changes category setting by changing category while using same color, 
Previous records with the particular color should have default color.

**Comment by Heathercoraje** [comment]
@veredrec What about previous records with color which are not repetitive?

**Comment by veredrec** [comment]
@Heathercoraje I'm not sure if I understand the question. What do you mean by records which are not repetitive?

**Comment by Heathercoraje** [comment]
We don't want this function no longer
