### ISSUE TITLE
TrashIcon inside Button does not do anything 

### ISSUE THREAD

**Issue by Heathercoraje** [Heathercoraje/pomotris-vh#55]

**Comment by Heathercoraje** [comment]
Could not fix problem so far :(
Posted on stackOverFlow for help

**Comment by veredrec** [comment]
@Heathercoraje do you mean the icon itself, right? Because clicking on the button does remove the record (but not clicking the trash icon :wastebasket:)

**Comment by Heathercoraje** [comment]
yeap. once I get some answers from stackoverflow.. I will have more ideas.
